# Generated by Django 4.2.1 on 2023-05-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_user_foto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user", name="foto", field=models.ImageField(upload_to=""),
        ),
    ]
